CREATE TABLE Customer(
	ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) DEFAULT NULL,
    contact VARCHAR(255) DEFAULT NULL,
    telephone VARCHAR(255) DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    remark Text,
    PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

